
batch_size_train: 64
batch_size_test: 64
image_res: 224
hidden_size: 768

optimizer: {opt: adamW, lr: 1e-4, weight_decay: 0.02}
schedular: {sched: cosine, lr: 1e-4, epochs: 20, min_lr: 1e-5, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 3, cooldown_epochs: 0}


mae:
  drop_path: 0.1
  global_pool: True

disaster_types:
    train_file: 'data/ds/consolidated_disaster_types_train_final.tsv'
    val_file: 'data/ds/consolidated_disaster_types_dev_final.tsv'
    test_file: 'data/ds/consolidated_disaster_types_test_final.tsv'

informativeness:
    train_file: 'data/ds/consolidated_info_train_final.tsv'
    val_file: 'data/ds/consolidated_info_dev_final.tsv'
    test_file: 'data/ds/consolidated_info_test_final.tsv'

humanitarian:
    train_file: 'data/ds/consolidated_hum_train_final.tsv'
    val_file: 'data/ds/consolidated_hum_dev_final.tsv'
    test_file: 'data/ds/consolidated_hum_test_final.tsv'

damage_severity:
    train_file: 'data/ds/consolidated_damage_train_final.tsv'
    val_file: 'data/ds/consolidated_damage_dev_final.tsv'
    test_file: 'data/ds/consolidated_damage_test_final.tsv'